version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      sentry:
        patterns:
          - "@sentry/*"
      vue:
        patterns:
          - "@vue/*"
          - "vue-*"
          - "vue"
      eslint:
        patterns:
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "prettier"
      jest:
        patterns:
          - "@jest/*"
          - "jest"
          - "ts-jest"
