enableGlobalCache: false

packageExtensions:
  "@swagger-api/apidom-ns-json-schema-draft-4@*":
    dependencies:
      "@swagger-api/apidom-ast": "*"
  "@swagger-api/apidom-ns-openapi-3-1@*":
    dependencies:
      "@swagger-api/apidom-ast": "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.45.cjs
