enableGlobalCache: false

packageExtensions:
  "@grpc/grpc-js@*":
    dependencies:
      "@types/long": "*"
  "@opentelemetry/otlp-transformer@*":
    dependencies:
      "@types/long": "*"
  swagger-ui@*:
    dependencies:
      autolinker: "*"
      btoa: "*"
      cookie: "*"
      deepmerge: "*"
      fast-json-patch: "*"
      fault: "*"
      formdata-node: "*"
      is-plain-object: "*"
      qs: "*"
      regenerator-runtime: "*"
      traverse: "*"
  vue-router@*:
    dependencies:
      "@vue/runtime-dom": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-4.0.0-rc.11.cjs
