compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@opentelemetry/instrumentation-mysql2@^0.34.0":
    dependencies:
      "@opentelemetry/sql-common": ^0.40.0

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs
