version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: SSH key for of-sound-mind.com
          command: ssh-keyscan of-sound-mind.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy Master to dokku staging
          command: git push dokku@of-sound-mind.com:roster-staging master
workflows:
  build-and-test:
    jobs:
      - node/test:
          version: 14.17.0
          pkg-manager: yarn
          name: test
      - node/test:
          version: 14.17.0
          pkg-manager: yarn
          run-command: build
          name: build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
