version: 2.1
orbs:
  node: circleci/node@4.4.0
  queue: eddiewebb/queue@1.5.0
parameters:
  node-version:
    type: string
    default: "16.13.0"
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: SSH key for of-sound-mind.com
          command: ssh-keyscan of-sound-mind.com >> ~/.ssh/known_hosts
      - queue/until_front_of_line
      - run:
          name: Deploy to dokku staging using preconfigured ssh key and server-side command
          command: ssh dokku@of-sound-mind.com
workflows:
  build-and-test:
    jobs:
      - node/test:
          version: << pipeline.parameters.node-version >>
          pkg-manager: yarn-berry
          run-command: jest
          cache-version: v3
          name: jest
      - node/test:
          version: << pipeline.parameters.node-version >>
          pkg-manager: yarn-berry
          run-command: pretty-check
          cache-version: v3
          name: pretty-check
      - node/test:
          version: << pipeline.parameters.node-version >>
          pkg-manager: yarn-berry
          run-command: lint
          cache-version: v3
          name: lint
      - node/test:
          version: << pipeline.parameters.node-version >>
          pkg-manager: yarn-berry
          run-command: build
          cache-version: v3
          name: build
      - deploy:
          requires:
            - jest
            - pretty-check
            - lint
            - build
          filters:
            branches:
              only:
                - master
