### This workflow has access to secrets and a read-write token
# based on https://github.com/RecapTime/verify/blob/main/.github/workflows/dependabot.yml
name: Fix Yarn lockfiles updated by Dependabot

on:
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types:
      - completed

jobs:
  fix-lockfiles:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "16"
      - name: Autofix lockfile
        run: |
          # restore yarn.lock from the previous commit
          git checkout HEAD^ -- yarn.lock
          # if package.json was not updated, upgrade the dependency
          git diff --name-only HEAD^ HEAD | grep -q 'package.json' || yarn up --mode=update-lockfile `git log -1 --pretty=%s | awk '{ print $2 }'`
          # restore package.json from the last commit
          git checkout HEAD -- package.json
          yarn install --no-immutable --mode=update-lockfile
          # deduplicate lockfile
          yarn dedupe
      - name: Config Git
        run: |
          git config --global user.name 'Nobody In Local'
          git config --global user.email 'june@of-sound-mind.com'
      - name: Commit changes
        run: |
          cd .`git log -1 --pretty=%s | awk '{ print $8 }'`
          git add yarn.lock
          git commit -m "chore(dependabot): fix broken Yarn lockfile" -m "Related-Issue: https://github.com/dependabot/dependabot-core/issues/1297" --signoff
          git push
